### ISSUE TITLE
add rdfs:label to all entity classes again

### ISSUE THREAD

**Issue by sennierer** [InTaVia/idm-rdf#11]
Just played around with the mockup data and it turns out that eg the basic-persons query doesnt work anymore as we do not have E21_Person -> rdfs:label -> literal in place anymore. For the API I guess it will very often happen that we just want to query a label for an entity, no matter if its the first name, an alternative name or the surname. As long as there are no severe reasons not to do this I wouls suggest to add rdfs:labels again to the entities (in addition to the appellation route).

**Comment by CarlaVS** [comment]
labels are added to entities in the test data set
