### ISSUE TITLE
bioc:has_gender bioc:painter

### ISSUE THREAD

**Issue by sennierer** [InTaVia/idm-rdf#13]
There is an error in the mockup data regarding bioc:gender

https://github.com/InTaVia/idm-rdf/blob/7df15e66c32c5e4f945b2c7a6b19ba06a12e8be7/test_dataset_designsprint/exdataset.rdf#L11543-L11545

**Comment by CarlaVS** [comment]
Typo in persons.csv for invented person Tina_t Blau_t, has been corrected.
