### ISSUE TITLE
bioc:Painter has wrong class

### ISSUE THREAD

**Issue by sennierer** [InTaVia/idm-rdf#14]
In relation to #13 there is a wrong class definition for bioc:painter in the mockup data
https://github.com/InTaVia/idm-rdf/blob/7df15e66c32c5e4f945b2c7a6b19ba06a12e8be7/test_dataset_designsprint/exdataset.rdf#L11543-L11545

**Comment by CarlaVS** [comment]
Typo in persons.csv for invented person Tina_t Blau_t, has been corrected.
