### ISSUE TITLE
IDM-RDF Event/ Period conflict

### ISSUE THREAD

**Issue by CarlaVS** [InTaVia/idm-rdf#2]
### In harmonizing Europeana and Cidoc CRM there is a conflict that has not yet been solved yet:

The EDM defines their class Event as a merge of Cidoc CRMs E5 Event and E4 Period+: "An event is a change “of states in cultural, social or physical systems, regardless of scale, brought about by a series or group of coherent physical, cultural, technological or legal phenomena” (E5 Event in CIDOC CRM) or a “set of coherent phenomena or cultural manifestations bounded in time and space” (E4 Period in CIDOC CRM)"

### That means that we have two opportunities (which both have disadvantages):
1. We unite E4 and E5 like in the EDM and append the Properties of both classes. In my opinion this would be problematic in our field of research because historic epochs are a relevant parameter and all E5 properties could be applied to .
2. We solve the problem by cleaning Europeana data. Some Sparqles with edm-properties which have Event as periods show that there is not a lot of event data (edm:wasPresentAt brings no results). But there are some values that we can see as Events (like historic epochs) when we look for other properties (like dc:date).

I think that Nr.1 is the better solution, but I'm nevertheless interested what you think about that conflict or if you have other suggestions to solve it.

**Comment by CarlaVS** [comment]
solved the conflict by removind edm:Event (solution 2 -> see IDM-RDF OWL file)

**Comment by GO5IT** [comment]
I guess it is already closed, and personally it seems more sensible to stick with the CIDOC-CRM way (ie keep 2 classes).
But perhaps it may be still worth investigating the fact by a bottom-up approach:

a) How many PDB data (in InTaVia) do we have for E5 Event and E4 Period?
a) How many ODB data do we have for E5 Event and E4 Period? (You did a bit for Europeana)

Then, select a practical way to come up with the best solution. It would be also a good idea to think of a best practice of modelling those concepts, if/when we enrich data with external identifiers for Period such as https://perio.do/en/ and https://dbpedia.org/page/Paleolithic, and events such as https://www.wikidata.org/wiki/Q361 (although the interpretation of two concepts are not the same for every user).

**Comment by sennierer** [comment]
seems to be resolved
