### ISSUE TITLE
BioCRM Properties for Thing Role

### ISSUE THREAD

**Issue by CarlaVS** [InTaVia/idm-rdf#3]
I can’t find a property in the old or updated BioCRM OWL which is the appropriate property to connect a Thing Role and a Thing. I have created a preliminary property for the IDM OWL to connect them ( rdfs:label "preliminary property \"has role\""). 
Did I get Thing Role wrong? Which property can be used here?

**Comment by yoge1** [comment]
The property for connecting a Thing Role and a Thing was missing in the Bio CRM schema (OWL). The property is the same one that is used for connecting an Actor Role and an Actor: bioc:inheres_in (and inverse property bioc:bearer_of). I modified the domain and range of these properties in the new version of Bio CRM schema:
https://github.com/SemanticComputing/biocrm/blob/master/bioc.ttl

**Comment by CarlaVS** [comment]
Thank you!
